import { NextResponse } from "next/server";
import { rateLimit } from "@/lib/rate-limit";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { generateResponse } from "@/lib/ai/router";
import { 
  loadStudentFullContext, 
  updateCopilotMemory, 
  getCompanyKnowledge, 
  executeCopilotAction 
} from "@/lib/db/copilot-engine";

export const dynamic = "force-dynamic";

const copilotInputSchema = z.object({
  message: z.string().trim().min(1, "Message is required.").max(10000, "Message exceeds length constraints."),
  history: z
    .array(
      z.object({
        role: z.string().trim(),
        content: z.string().trim(),
      })
    )
    .optional()
    .nullable(),
});

// Multi-Agent Router classification logic
function routeQuestion(query: string): { agent: string; instruction: string; provider: "gemini" | "groq" | "openrouter"; model?: string } {
  const q = query.toLowerCase();
  
  // Cost Optimization Layer: Default to Groq/OpenRouter for standard queries, use Gemini for complex ones
  let useGemini = false;
  let agent = "Career Agent";
  let promptDetails = "You are the Career Agent, focusing on general learning roadmaps, career strategy, and general platform queries.";

  if (q.includes("resume") || q.includes("cv") || q.includes("ats") || q.includes("enhance") || q.includes("rewrite")) {
    agent = "Resume Agent";
    useGemini = true; // Resume rewrite/ATS requires deep Gemini reasoning
    promptDetails = "You are the Resume Agent. Analyze ATS scores, suggest keywords, rewrite bullets using the STAR method, and verify action verbs.";
  } else if (q.includes("interview") || q.includes("star") || q.includes("answer") || q.includes("mock")) {
    agent = "Interview Agent";
    useGemini = true; // Evaluation requires deep Gemini reasoning
    promptDetails = "You are the Interview Agent. Review mock scores, evaluate STAR formatted interview behavior, and give specific response improvements.";
  } else if (q.includes("coding") || q.includes("algo") || q.includes("dsa") || q.includes("complexity") || q.includes("complexity") || q.includes("array") || q.includes("graph")) {
    agent = "DSA Agent";
    useGemini = false; // Code hints can be handled by free OS models
    promptDetails = "You are the DSA Agent. Provide optimized algorithm hints, time/space complexity analyses, and dry-run explanations.";
  } else if (q.includes("google") || q.includes("amazon") || q.includes("deloitte") || q.includes("tcs") || q.includes("infosys") || q.includes("accenture")) {
    agent = "Company Agent";
    useGemini = false; // Company templates are factual/RAG based
    promptDetails = "You are the Company Agent. Reference specific company round structures, target roles requirements, and resource links.";
  } else if (q.includes("email") || q.includes("cold") || q.includes("referral") || q.includes("linkedin") || q.includes("network")) {
    agent = "Recruiter Agent";
    useGemini = false; // Cold emails templates can be generated by free OS models
    promptDetails = "You are the Recruiter Agent. Draft high-conversion cold emails, referral pitches, and networking templates.";
  }

  // Choose provider based on optimization logic
  let provider: "gemini" | "groq" | "openrouter" = "gemini";
  let model = "gemini-3.5-flash";

  if (!useGemini) {
    if (process.env.GROQ_API_KEY) {
      provider = "groq";
      model = "llama-3.1-8b-instant";
    } else if (process.env.OPENROUTER_API_KEY) {
      provider = "openrouter";
      model = "meta-llama/llama-3.3-70b-instruct:free";
    }
  }

  return { agent, instruction: promptDetails, provider, model };
}

// Main POST conversational handler re-engineered
export async function POST(request: Request) {
  const startTime = Date.now();
  try {
    // 1. Rate limiting check (50 requests/hour)
    const ip = request.headers.get("x-forwarded-for") || "127.0.0.1";
    const limitResult = await rateLimit(ip, "copilot");
    if (!limitResult.success) {
      return NextResponse.json(
        { success: false, message: "Rate limit exceeded. Please try again later." },
        { status: 429, headers: limitResult.headers }
      );
    }

    // 2. Auth user session
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    const userId = user?.id || "guest-user";

    // 3. Input validation
    const body = await request.json().catch(() => ({}));
    const validation = copilotInputSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { success: false, message: "Invalid message payload schema." },
        { status: 400 }
      );
    }
    const { message, history } = validation.data;

    // AI Abuse Check (Prompt injection and loop protections)
    const { detectPromptAbuse } = await import("@/lib/ai-abuse");
    const abuseCheck = detectPromptAbuse(message);
    if (abuseCheck.abused) {
      // Log security incident to database
      try {
        await supabase.from("security_incidents").insert({
          event_type: "token_abuse",
          ip_address: ip,
          user_id: userId === "guest-user" ? null : userId,
          details: { reason: abuseCheck.reason, input: message }
        });
      } catch (err) {
        console.error("Failed to log security incident:", err);
      }

      return NextResponse.json(
        { success: false, message: `Security restriction triggered: ${abuseCheck.reason}` },
        { status: 400 }
      );
    }

    // 4. Fetch Deep Student Context from database
    const context = await loadStudentFullContext(userId, supabase);

    // 5. Intercept Actions intent (Phase 4 Action Engine)
    let actionTag: string | null = null;
    let actionNotice = "";
    const msgLower = message.toLowerCase();

    if (msgLower.includes("save") && (msgLower.includes("job") || msgLower.includes("role"))) {
      const matchCompany = message.match(/(?:at|for)\s+([A-Z][a-zA-Z]+)/);
      const companyVal = matchCompany ? matchCompany[1] : "Target Company";
      const actionRes = await executeCopilotAction(userId, "SAVE_JOB", {
        company: companyVal,
        role: context.targetRole || "Software Engineer",
        status: "Saved"
      }, supabase);
      if (actionRes.success) {
        actionTag = "OPEN_CRM";
        actionNotice = `\n\n*(Action executed: ${actionRes.message})*`;
      }
    } else if (msgLower.includes("schedule") && (msgLower.includes("prep") || msgLower.includes("roadmap"))) {
      const actionRes = await executeCopilotAction(userId, "SCHEDULE_ROADMAP", {}, supabase);
      if (actionRes.success) {
        actionTag = "OPEN_ROADMAP";
        actionNotice = `\n\n*(Action executed: ${actionRes.message})*`;
      }
    }

    // 6. Placement Intelligence Engine (Phase 5 diagnostics)
    let diagnosticNotice = "";
    if (context.atsScore < 70 && context.applications.length > 15) {
      diagnosticNotice = "\n\n> [!WARNING]\n> **Diagnostic Alert**: I noticed you have submitted over 15 applications but your ATS Resume score is under 70%. Your highest impact priority is improving resume bullet metrics to pass initial screenings.";
      // Log weakness
      if (!context.weaknesses.includes("Resume structure")) {
        context.weaknesses.push("Resume structure");
        await updateCopilotMemory(userId, context, supabase);
      }
    } else if (context.atsScore >= 80 && context.applications.filter(a => a.status === "Interview").length > 3) {
      diagnosticNotice = "\n\n> [!TIP]\n> **Diagnostic Alert**: Great ATS score! You have active scheduled interviews. Focus heavily on STAR behavioural preparation patterns with my Interview Agent.";
    }

    // 7. Predictive Placement Scoring (Phase 7 probabilities)
    const resumeQualityWeight = context.atsScore * 0.35;
    const interviewWeight = context.mockInterviewsAvg * 0.35;
    const portfolioWeight = (context.portfolioStatus.portfolio ? 5 : 0) + (context.portfolioStatus.github ? 5 : 0);
    const projectsWeight = Math.min(context.projectsCount * 5, 15);
    const crmWeight = Math.min(context.applicationsCount * 1.5, 10);
    
    const probabilityScore = Math.min(Math.round(resumeQualityWeight + interviewWeight + portfolioWeight + projectsWeight + crmWeight), 98);

    const predictiveMetrics: string[] = [];
    if (context.atsScore < 90) {
      predictiveMetrics.push(`+${Math.round((90 - context.atsScore) * 0.35)}% if ATS score reaches 90%`);
    }
    if (context.projectsCount < 3) {
      predictiveMetrics.push(`+${(3 - context.projectsCount) * 5}% if another project is added`);
    }
    if (context.assessmentAccuracy < 80) {
      predictiveMetrics.push("+6% if overall SQL assessment exceeds 80% accuracy");
    }

    // 8. AI Generated Missions (Phase 9 personalized gamification)
    let dynamicMission = { title: "Complete Aptitude percentage assessment", reward: "30 XP" };
    if (context.techStack.includes("Python") || context.techStack.includes("SQL")) {
      dynamicMission = { title: "Complete SQL Join Assessment", reward: "40 XP" };
    } else if (context.techStack.includes("Java") || context.techStack.includes("Spring")) {
      dynamicMission = { title: "Verify Spring API custom project link", reward: "60 XP" };
    }

    // 9. Autonomous Daily Placement plan (Phase 10 daily directives)
    const dailyPlan = [
      `Improve ATS score by ${Math.max(85 - context.atsScore, 5)} points`,
      `Complete 1 timed custom drill on ${context.weaknesses[0] || "Aptitude"}`,
      `Track 2 new job applications in CRM board`,
      `Review STAR question responses with AI Coach`
    ];

    // 10. Multi-Agent Router classification
    const routing = routeQuestion(message);

    // 11. Retrieve company specific RAG knowledge base items
    let companyRAG = "";
    if (routing.agent === "Company Agent") {
      const matchCompany = message.match(/(?:deloitte|google|amazon|tcs|infosys|accenture)/i);
      if (matchCompany) {
        const companyName = matchCompany[0];
        const data = await getCompanyKnowledge(companyName, undefined, supabase);
        if (data) {
          companyRAG = `COMPANY INTEL FILE (${data.company}):
- Target role: ${data.role}
- Hiring Process: ${JSON.stringify(data.hiring_process)}
- Experience: ${data.interview_experience}`;
        }
      }
    }

    // 12. Construct system instruction prompt
    const systemPrompt = `You are the ${routing.agent} of BuggedBrain Placement OS. 
Your goal is to guide this student:
- Target Role: ${context.targetRole}
- Tech Stack: ${context.techStack.join(", ")}
- Current ATS Resume score: ${context.atsScore}%
- Current PRI Score: ${context.priScore}
- Diagnostic Level: ${context.placementLevel}
- Strengths: ${context.strengths.join(", ")}
- Weaknesses: ${context.weaknesses.join(", ")}
- Repeated Mistakes: ${context.repeatedMistakes.join(", ")}

Agent Focus instruction:
${routing.instruction}

${companyRAG}

CRITICAL INSTRUCTIONS:
1. Speak in your specialized agent persona. Customize advice to the user's specific skills and weaknesses.
2. Structure your markdown output with headers, bullet lists, and code blocks to make it look premium.
3. If user requests actions (like saving jobs) refer to the success of the action.`;

    const gatewayResponse = await generateResponse({
      provider: routing.provider,
      model: routing.model,
      prompt: `CONVERSATION HISTORY:\n${(history || []).map(h => `${h.role.toUpperCase()}: ${h.content}`).join("\n")}\n\nUSER: ${message}`,
      systemInstruction: systemPrompt,
      temperature: 0.4,
      taskType: "placement_copilot",
      userId
    });

    if (!gatewayResponse.success) {
      return NextResponse.json(
        { success: false, message: `Multi-agent routing failure: ${gatewayResponse.error}` },
        { status: 500 }
      );
    }

    // 13. Construct output payload
    const replyText = gatewayResponse.text + actionNotice + diagnosticNotice;

    const { generateProactiveInsights, generateCoachPlan } = await import("@/lib/ai-agent");
    const proactiveInsights = generateProactiveInsights(context);
    const coachPlan = generateCoachPlan(context);

    const responsePayload = {
      success: true,
      data: {
        reply: replyText,
        action: actionTag,
        healthReport: {
          resumeQuality: context.atsScore,
          interviewReadiness: context.mockInterviewsAvg,
          projects: Math.min(context.projectsCount * 33, 100),
          overallReadiness: context.priScore
        },
        predictiveScore: probabilityScore,
        predictiveMetrics,
        dailyPlan,
        dynamicMission,
        proactiveInsights,
        coachPlan
      }
    };

    return NextResponse.json(responsePayload, { status: 200 });

  } catch (err: any) {
    console.error("AI Copilot API error:", err);
    return NextResponse.json(
      { success: false, message: err?.message || "Temporary issue." },
      { status: 500 }
    );
  }
}
